### PR TITLE
Updating Dynamics 365 Finance and Operations Tools Task IDs to versio…

### PR DESCRIPTION
**Pull request by Moutasema**
…n 0.2.73

### CODE REVIEW

**Comment by valerymoskalenko** [comment]
@Moutasema Thank you! You save my day!

**Comment by turbozapekanka** [comment]
@jorisdg merge this please

**Comment by jorisdg** [comment]
Unfortunately merging this will fix this maybe for you, but will break it for other people. The GUIDs shown in this sample are the ACTUAL guids of the tasks. The Azure DevOps team so far has been unable to explain why or what is happening that there are many accounts who get a different guid for some reason.

**Comment by ghost** [comment]
Thanks this fixed it for me as well!

**Comment by matejskubic** [comment]
@jorisdg these GUIDs are defined in [Dynamics 365 Finance and Operations Tools](https://marketplace.visualstudio.com/items?itemName=Dyn365FinOps.dynamics365-finops-tools) DevOps Pipeline Extension and are equal for all users.

For example task for updating model version is defined in `task.json` and GUID is defined there and will not change until the publisher decides so. 

```json
{
    "id": "39fb981e-bf08-50cc-a6b1-57bd7d8024fd",
    "name": "XppUpdateModelVersion",
    "friendlyName": "Update Model Version"  
}
```

**Comment by jorisdg** [comment]
I still can't explain why these GUIDs are off. Our internal source code for the extension (and all of our test AZDO accounts) have the GUIDs as you seem them here.
I downloaded the extension and extracted it and the GUIDs in there are what's proposed in this PR. I can't explain it, but I'll take this PR. Thanks for pushing this again.

**Pull request merged**
